root: true
env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': 'off'
overrides:
  - files: tests/**/*.ts
    env:
      jest/globals: true
    plugins:
      - jest
    rules:
      'no-empty-pattern': 'off'
      '@typescript-eslint/interface-name-prefix': 'off'
      '@typescript-eslint/no-empty-function': 'off'
      '@typescript-eslint/no-unused-vars': 'off'
