name: Run Jest tests
on:
  push:
    paths:
      - '**.ts'
      - 'jest.config.js'

jobs:
  build:
    name: Jest tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn test
