name: on push task
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Yarnキャッシュディレクトリパス取得
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Check ESLint
        run: yarn lintjs:fix
      - name: was auto-fix happen in check
        run:
      - name: Run TypeScript test
        run: yarn test
      - name: Push auth-fixed ESLint errors
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${{ github.event.pusher.name }"
          git config --global user.email "${{ github.event.pusher.email }}"

  release:
    name: Release to npm
    if: github.ref == 'refs/head/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
